@startuml
'https://plantuml.com/sequence-diagram

autonumber

Client -> Server: 결제 요청 (Kakao Pay)
Server -> Kakao_API: 결제 준비 (Ready)

Server <-- Kakao_API: approval_url 로 redirect (with pg_token)
Server -> Kakao_API: 결제 승인 (Approve)
Server <-- Kakao_API: approval response
Client <-- Server: 결제 승인
@enduml