spring:
  application:
    name: tickit-api
  datasource:
    url: jdbc:mysql://localhost:3306/tickit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret-key: 9fde0a405b323d8cf7b9bc0a39e205ed320b0364d1adfba467eac36aaa8a50d9

upload:
  path: ./performance_poster

kakao:
  api:
    app-key: 0c7b3db8206e128a2fc341c21acfc4bd
    redirect-uri: http://localhost:8080/kakao/login/authorize
    key: "DEV9C84DDEF4431A52CE884EDB0EE8F9CEA33B86"
    cid: TC0ONETIME
    approval-url: http://localhost:8080/api/pay/approve
    cancel-url: http://localhost:8080/cancel
    fail-url: http://localhost:8080/fail