spring:
  application:
    name: tickit-api

kakao:
  api:
    key: "DEV9C84DDEF4431A52CE884EDB0EE8F9CEA33B86"
    cid: TC0ONETIME
    approval-url: http://localhost:8080/api/pay/approve
    cancel-url: http://localhost:8080/cancel
    fail-url: http://localhost:8080/fail